var jsList = [
    "src/res/commonJs.js",
    "src/res/lhJs.js",
    "src/resource.js",
    "src/config/hsb_cfg.js",
    "src/common/funcs.js",
    "src/common/funcs2.js",
    "src/common/items.js",
    "src/layer/layerControl.js",
    "src/layer/myLayer.js",
    "src/layer/mainLayer.js",
    "src/layer/doLayer.js",
    "src/layer/helpLayer.js",
    "src/layer/seeLayer.js",
    "src/dialog/dialogControl.js",
    "src/dialog/exitDialog.js",
    "src/dialog/quitExpDialog.js",
    "src/dialog/tipsDialog.js",
    "src/dialog/judgeDialog.js",
    "src/common/extra.js",
    "src/common/timerControl.js",

    "src/extra/hsb/learnLayer.js",
    "src/extra/hsb/seeExp1.js",
    "src/extra/hsb/doExp1.js",
]