var jsList = [
    "src/res/commonJs.js",
    "src/res/lhJs.js",
    "src/resource.js",
    "src/config/rtdqg_cfg.js",
    "src/common/funcs.js",
    "src/common/funcs2.js",
    "src/common/items.js",
    "src/layer/layerControl.js",
    "src/layer/myLayer.js",
    "src/layer/mainLayer.js",
    "src/layer/doLayer.js",
    "src/layer/helpLayer.js",
    "src/layer/seeLayer.js",
    "src/dialog/dialogControl.js",
    "src/dialog/exitDialog.js",
    "src/dialog/quitExpDialog.js",
    "src/dialog/tipsDialog.js",
    "src/dialog/judgeDialog.js",
    "src/common/extra.js",
    "src/common/timerControl.js",

    "src/extra/rtdqg/learnLayer.js",
    "src/extra/rtdqg/seeExp1.js",
    "src/extra/rtdqg/doExp1.js",
    "src/extra/rtdqg/videoLayer.js",
]